
// This file contains mock responses for AI features until you connect to a real AI API

export const getMockHoroscopeReading = (sign: string) => {
  const horoscopes = {
    aries: "Today is a powerful day for taking action on your goals, Aries. Your ruling planet Mars is fueling your natural fire, giving you an extra boost of energy and determination. Use this cosmic gift wisely by focusing on your most important priorities. Unexpected opportunities may arise in your career sector, so stay alert and ready to seize the moment. Your confidence is magnetic now – others will be drawn to your leadership and passion. In relationships, express your desires clearly but remember to listen as well. Balance your assertiveness with patience for best results.",
    taurus: "Stability and comfort are highlighted for you today, Taurus. Venus is blessing your financial sector, potentially bringing unexpected resources or opportunities your way. This is an excellent time to evaluate your material goals and make practical plans for the future. Your natural persistence will serve you well in current projects. In relationships, your loyalty and dependability shine through, strengthening bonds with loved ones. Take time to appreciate beauty around you – perhaps through nature, art, or good food. Your practical wisdom is especially valuable to others now.",
    gemini: "Your mind is exceptionally sharp today, Gemini. Mercury's position enhances your already impressive communication skills, making this an ideal time for important conversations, writing projects, or presentations. New information may come your way that changes your perspective on a long-standing situation. Social connections are highlighted – an unexpected message from someone in your network could lead to exciting opportunities. Balance intellectual pursuits with physical movement to maintain your energy. Your adaptability is your superpower today – flow with changes rather than resisting them.",
    cancer: "Emotional insights flow freely today, Cancer. The Moon, your ruling celestial body, is enhancing your intuitive abilities and emotional intelligence. Pay attention to your dreams and inner feelings, as they contain valuable guidance. Home and family matters take center stage – perhaps it's time for a heartfelt conversation with a loved one or making your living space more nurturing. Your natural caregiving abilities are appreciated by others now. Balance giving to others with self-care for optimal wellbeing. Trust your instincts in financial decisions today.",
    leo: "Your natural radiance is amplified today, Leo. The Sun is highlighting your creative talents and leadership abilities, making this an excellent time to take center stage in projects that showcase your unique gifts. Romance and play are favored – make time for activities that bring you joy and self-expression. A burst of inspiration may lead to a breakthrough in a creative blockage. Your generosity and warmth draw others to you now. Balance your desire for recognition with genuine appreciation for those who support you. Bold moves in career matters are favored under this cosmic influence.",
    virgo: "Details matter even more than usual today, Virgo. Your analytical abilities are heightened, allowing you to solve problems that have stumped others. This is an excellent time for organizing, planning, and implementing practical systems that improve efficiency. Health matters are highlighted – small adjustments to your daily routine could yield significant benefits. Your helpful nature is appreciated in work environments, though be careful not to take on too many responsibilities. Balance your critical thinking with compassion, especially in communications with loved ones. Your meticulous approach creates lasting value.",
    libra: "Harmony and balance are your themes today, Libra. Venus enhances your natural diplomatic abilities, making this an ideal time for mediating conflicts or negotiating agreements. Beauty calls to you – perhaps through art, design, or enhancing your personal style. Relationships of all kinds are highlighted, with opportunities to deepen connections through meaningful conversation. Your sense of fairness makes you a valued friend and colleague. Balance socializing with periods of solitude to maintain your inner equilibrium. Trust your aesthetic judgment in making choices today.",
    scorpio: "Transformation is in the air today, Scorpio. Pluto's intense energy amplifies your natural ability to see beneath surfaces and understand hidden motivations. This is a powerful time for research, investigation, and tackling topics others might avoid. Financial matters may require your attention, possibly involving shared resources. Your emotional depth and loyalty make you an invaluable support to those in your inner circle. Balance intensity with moments of lightness and relaxation. Trust your ability to emerge stronger through challenges – resilience is your special gift.",
    sagittarius: "Adventure calls to you today, Sagittarius. Jupiter's expansive energy fuels your natural love of exploration and learning. This is an excellent time for study, travel planning, or broadening your horizons through new experiences. Philosophical questions engage your mind, perhaps leading to important insights about your life path. Your optimism is contagious, lifting the spirits of those around you. Balance your quest for new frontiers with attention to practical details. Your ability to see the big picture provides valuable perspective to others. Follow your enthusiasm toward meaningful growth.",
    capricorn: "Achievements and long-term goals are highlighted today, Capricorn. Saturn's disciplined energy strengthens your natural ambition and persistence. This is an excellent time for career planning, setting concrete objectives, or taking on responsibilities that showcase your leadership abilities. Financial matters are favored, particularly long-term investments and planning. Your pragmatic approach and reliability make you indispensable in work environments. Balance your dedication to success with quality time for personal relationships. Your capacity for steady progress toward goals is unmatched.",
    aquarius: "Innovation and social connections are highlighted today, Aquarius. Uranus enhances your natural visionary thinking, potentially bringing flashes of insight that solve longstanding problems. This is an excellent time for group activities, community involvement, or advancing humanitarian causes close to your heart. Technology and forward-thinking projects are favored. Your unique perspective is especially valuable now – don't hesitate to share your unconventional ideas. Balance your intellectual focus with attention to emotional needs, both yours and others'. Your ability to envision better futures creates positive change.",
    pisces: "Intuition and creativity flow abundantly today, Pisces. Neptune enhances your natural spiritual awareness and artistic sensibilities. This is a wonderful time for creative projects, meditation, or compassionate service to others. Your boundaries may need attention – practice distinguishing between your emotions and those you're absorbing from others. Dreams and daydreams contain valuable messages now, so pay attention to your inner world. Your empathy makes you a healing presence for loved ones. Balance your compassion for others with healthy self-care. Trust the wisdom of your heart to guide your decisions."
  };

  const defaultHoroscope = "The cosmic energies today are aligning to bring you clarity and insight. It's a favorable time to reflect on your goals and make adjustments where needed. Your intuition is especially strong now – trust the inner guidance you're receiving. Relationships may require extra attention, but honest communication will strengthen important bonds. Take care of your physical well-being alongside your spiritual and emotional needs. The universe supports your authentic path forward.";

  return horoscopes[sign.toLowerCase() as keyof typeof horoscopes] || defaultHoroscope;
};

export const getMockTarotReading = (cardName: string) => {
  const readings = {
    "the fool": "The Fool appears in your reading today as a messenger of new beginnings and unlimited potential. The universe is encouraging you to take a leap of faith and trust in the journey ahead, even if you cannot see where the path leads. Like the Fool, approach life with childlike wonder and openness. This card suggests you're at a point where you can make a fresh start, unburdened by past expectations or failures. The energy around you supports bold moves and spontaneous decisions. However, remember that the Fool also carries wisdom in his seeming innocence – stay alert to practical realities even as you embrace adventure. This is a time to listen to your heart over logical objections and trust that the universe will support your authentic path forward.",
    "the magician": "The Magician arrives in your reading as a powerful symbol of manifestation and personal power. All the elements you need to create your desired reality are already within and around you – you simply need to direct your will and energy with intention. This card indicates that you have the skills, tools, and capabilities necessary to achieve your goals. The universe is supporting your creative efforts now, so this is an excellent time to start new projects, particularly those requiring focus and determination. The Magician reminds you that you are the conscious creator of your life, capable of transforming ideas into reality through focused action. Connect your spiritual awareness with practical steps, and remember that your thoughts create energy – direct them wisely and with purpose.",
    "the high priestess": "The High Priestess graces your reading today, bringing messages from the realm of intuition and the subconscious mind. Her appearance suggests that the answers you seek lie within you, beneath the surface of conscious thought. This is a time to trust your inner knowing above external advice or conventional wisdom. Pay attention to your dreams, sudden insights, and gut feelings – they contain valuable guidance now. The High Priestess also indicates that certain elements of your situation remain hidden or are not yet ready to be revealed. Practice patience and receptivity rather than forcing outcomes. Meditation, journaling, or time spent in nature may help you access the deep wisdom she represents. Honor the divine feminine energy within yourself, regardless of your gender – the intuitive, receptive, and mysterious aspects of existence.",
    "the empress": "The Empress blesses your reading with her abundant, nurturing energy. Her appearance signifies a time of growth, creativity, and connection to the natural world. This card suggests that your efforts are bearing fruit, whether literally in the form of pregnancy or birth for some, or metaphorically through creative projects and relationships that are flourishing. The Empress encourages you to embrace sensuality, beauty, and pleasure in your life without guilt or restriction. This is an excellent time to nurture yourself and others, to create comfortable and harmonious environments, and to express your creative ideas. Connect with nature to amplify these energies – even small actions like tending to plants or spending time outdoors can help. Remember that to nurture others effectively, you must first fill your own cup.",
    "the emperor": "The Emperor stands in your reading as a symbol of structure, authority, and solid foundations. His appearance suggests that now is a time to establish order, create clear boundaries, and implement practical systems in your life. This card often indicates the need for logical thinking and firm leadership, either from yourself or from a significant figure in your life. The Emperor reminds you of the importance of discipline and consistency in achieving your goals. While his energy may feel restrictive compared to more flowing cards, remember that appropriate structures create the stability needed for true freedom and growth. Consider where you might benefit from more organization, clear rules, or assertive action. The Emperor also represents father figures and society's structures – reflect on how these influences have shaped you and which aspects serve your highest good.",
    "the star": "The Star shines in your reading as a beacon of hope, inspiration, and spiritual connection. After periods of challenge or difficulty, this card arrives as a cosmic signal that healing and renewal are flowing into your life. The Star represents a time of faith restored and emotional wounds being cleansed. Its appearance suggests that you are—or soon will be—aligned with your authentic purpose and connected to divine guidance. This is an excellent time for meditation, spiritual practices, or any activity that helps you connect with your highest vision for your life. The Star encourages generosity and reminds you that giving and receiving are part of the same cosmic flow. Allow yourself to be vulnerable and open; release perfectionism and trust that you are exactly where you need to be on your journey. The universe supports your authentic path forward.",
    "the moon": "The Moon illuminates your reading with its mysterious, silvery light, bringing attention to the realm of the subconscious and intuition. This card suggests that not everything in your current situation is as it appears on the surface—there are deeper currents and hidden aspects still to be revealed. The Moon often appears when we're navigating uncertain territory without clear maps or guidelines. You may be experiencing confusing emotions, vivid dreams, or heightened sensitivity now. Rather than fighting this uncertainty, the card encourages you to develop trust in your intuitive navigation. Pay attention to recurring symbols, emotional patterns, and intuitive hits. The Moon also represents cycles and natural rhythms—consider how your current experience might be part of a larger pattern of growth. This is not a time for purely logical decisions but for honoring your deeper knowing, even when it doesn't make rational sense.",
    "the sun": "The Sun radiates joyful energy into your reading, bringing illumination, vitality, and success. This card is one of the most positive in the tarot, suggesting that you are—or soon will be—experiencing a time of clarity, achievement, and authentic self-expression. The Sun's appearance indicates that the confusions and obstacles of the past are burning away in the light of truth and new awareness. This is an excellent time for celebrating accomplishments, expressing your unique gifts, and approaching life with childlike enthusiasm. The Sun encourages optimism and confirms that you're on the right path. Its energy supports all forms of growth, healing, and creative expression. If you've been feeling low or stuck, The Sun promises revitalization and renewed purpose. Allow yourself to be seen and appreciated; let your light shine without dimming it for others' comfort.",
    "death": "Death appears in your reading not as a literal end of life, but as a powerful symbol of transformation and renewal. This card signals that a significant phase or cycle in your life is concluding to make way for new growth. While the process of release and transition can be challenging, Death reminds us that endings are a natural and necessary part of life's cycle. Something needs to be released now—perhaps an outdated belief, a relationship that has served its purpose, or a way of living that no longer supports your evolution. This card encourages you to surrender to this process rather than resisting the inevitable changes. Death clears away what is no longer vital so that new energy can flow in. Though the unknown future may seem intimidating, trust that this transformation is leading you toward greater authenticity and renewal. What appears to be a loss now may later be recognized as a liberation.",
    "the tower": "The Tower strikes in your reading with its lightning bolt of sudden change and revelation. This powerful card indicates that structures in your life that have been built on shaky foundations—perhaps false beliefs, unsustainable situations, or inauthenticity—are due for dramatic dismantling. While Tower experiences can feel shocking and disruptive, they ultimately serve to break through illusions and create space for more authentic rebuilding. The unexpected events associated with this card often initially appear as setbacks but ultimately lead to liberation from restrictive circumstances. The Tower encourages radical honesty with yourself about what isn't working in your life. Rather than clinging to the familiar, allow outmoded structures to fall away so that something more aligned with your true self can eventually be constructed. Remember that destruction precedes creation in many natural cycles.",
    "the lovers": "The Lovers card appears in your reading, signifying profound connection, choice, and alignment with your values. This card speaks to relationships of all kinds - romantic partnerships, yes, but also your relationship with yourself and your core beliefs. You may be facing an important decision that requires you to determine what you truly value. The Lovers encourages integration of seemingly opposing forces - masculine and feminine, logical and intuitive, physical and spiritual. In relationships, this card suggests deep harmony and mutual respect, or the potential for such connections to develop. This is an excellent time to examine whether your choices and relationships reflect your authentic self. The presence of The Lovers indicates that love and connection are central themes in your current journey, with opportunities for growth through vulnerability and honest communication.",
    "wheel of fortune": "The Wheel of Fortune spins into your reading, bringing messages of cyclical change and the natural ebb and flow of life circumstances. This powerful card reminds us that nothing remains static - good or challenging times are always temporary as the wheel continues to turn. Its appearance often signals a significant turning point or shift in fortune. You may be entering a period of positive opportunity after difficulty, or being reminded to appreciate current blessings as all things transform in time. The Wheel teaches us about surrendering to the natural cycles of existence while maintaining inner equilibrium regardless of external circumstances. Rather than resisting change, the card encourages you to adapt and flow with life's natural progression. Consider how you might consciously participate in your destiny while accepting what lies beyond your control. This is an excellent time for perspective-taking and recognizing the larger patterns in your life journey."
  };

  const defaultReading = "This card comes to you as a meaningful messenger from the universe. Its appearance in your reading suggests that you're at an important juncture on your path. The energies surrounding this card invite you to reflect deeply on its imagery and symbolism as they relate to your current situation. Trust that this card has appeared exactly when you needed its particular wisdom. Consider both traditional interpretations and your own intuitive response to this card – your personal connection with it contains valuable guidance. Whether its message brings challenge or comfort, know that it arrives to support your highest growth and authentic journey forward.";

  return readings[cardName.toLowerCase() as keyof typeof readings] || defaultReading;
};

export const getMockBotResponse = (question: string) => {
  // Handle different categories of questions with specific responses
  const lowerQuestion = question.toLowerCase();
  
  // Love and relationship responses
  if (lowerQuestion.includes('love') || lowerQuestion.includes('relationship') || lowerQuestion.includes('partner') || lowerQuestion.includes('marriage')) {
    return "The cosmic energies around your love life are intriguing right now. Venus is highlighting the importance of authentic communication and emotional vulnerability. If you're in a relationship, this is an excellent time to deepen your connection through meaningful conversations about your needs and dreams. If you're single, the stars suggest that being genuinely yourself will attract partners who appreciate your unique qualities. Rather than focusing on finding the 'perfect' person, consider how you can become more open to giving and receiving love. The universe often brings romantic opportunities when we're focused on personal growth rather than searching externally. Trust that love arrives in the right form and timing for your soul's journey.";
  }
  
  // Career and work responses
  if (lowerQuestion.includes('career') || lowerQuestion.includes('job') || lowerQuestion.includes('work') || lowerQuestion.includes('profession')) {
    return "Your career path is receiving significant cosmic attention right now. The planetary alignments suggest you're in a phase where your unique talents can be recognized and valued, particularly if you're willing to step outside your comfort zone. There may be opportunities emerging that align more authentically with your deeper purpose, even if they don't immediately seem logical by conventional standards. Trust the subtle nudges guiding you toward work that feels energizing rather than depleting. This is also an excellent time for developing new skills or perspectives that enhance your professional offerings. Remember that meaningful work isn't always about dramatic changes—sometimes it's about bringing a fresh approach or deeper presence to your current role.";
  }
  
  // Money and finances responses
  if (lowerQuestion.includes('money') || lowerQuestion.includes('finance') || lowerQuestion.includes('wealth') || lowerQuestion.includes('investment')) {
    return "The cosmic energies around your financial situation are highlighting the connection between your values and your resources. This is an excellent time to reflect on what true abundance means to you beyond societal definitions. The stars suggest that aligning your spending and earning with your authentic priorities will create more sustainable prosperity than simply pursuing financial gain for its own sake. Pay attention to subtle insights about your relationship with money—patterns established in childhood may be influencing your current financial decisions. Practical steps combined with a mindful approach to resources are favored now. The universe supports steady progress rather than quick fixes where finances are concerned.";
  }
  
  // Health and wellness responses
  if (lowerQuestion.includes('health') || lowerQuestion.includes('wellness') || lowerQuestion.includes('healing') || lowerQuestion.includes('sick')) {
    return "The celestial patterns affecting your health and wellbeing are emphasizing the mind-body-spirit connection right now. The stars suggest that emotional balance is particularly important for your physical vitality during this period. Pay attention to how different foods, environments, and relationships affect your energy levels. Small, consistent self-care practices will be more beneficial than dramatic but unsustainable health regimens. The cosmos supports holistic approaches—consider where traditional wisdom might complement modern health practices in your particular situation. Listen closely to your body's subtle signals rather than pushing through discomfort. This is also an excellent time for establishing rhythms and routines that honor your unique constitution and energy patterns.";
  }
  
  // Spiritual growth responses
  if (lowerQuestion.includes('spiritual') || lowerQuestion.includes('meditation') || lowerQuestion.includes('purpose') || lowerQuestion.includes('soul')) {
    return "The cosmic energies are particularly supportive of your spiritual growth at this time. The current planetary alignments are opening channels for deeper awareness and connection to your higher self. You may notice increased synchronicities, meaningful dreams, or moments of unexpected clarity. This is an excellent period for meditation, journaling, or any practice that helps you quiet external noise and listen to your inner wisdom. The stars suggest that answers you've been seeking externally may actually be found within you. Pay attention to what brings you a sense of meaning and alignment—these are cosmic breadcrumbs leading you toward your authentic path. Remember that spiritual growth often occurs in spirals rather than straight lines, so honor wherever you are in your unique journey.";
  }
  
  // Astrological responses based on zodiac mentions
  const zodiacSigns = ['aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo', 'libra', 'scorpio', 'sagittarius', 'capricorn', 'aquarius', 'pisces'];
  
  for (const sign of zodiacSigns) {
    if (lowerQuestion.includes(sign)) {
      return `As a ${sign.charAt(0).toUpperCase() + sign.slice(1)}, you're currently experiencing the influence of significant planetary movements. The cosmic energies are highlighting your natural ${getZodiacTraits(sign)} while inviting growth in areas that may feel less comfortable. This is an excellent time to leverage your innate strengths while being open to developing complementary qualities. The stars suggest that balance is key to navigating your current circumstances effectively. Pay attention to both your intuitive impressions and practical considerations as you make decisions. Your ruling planet is providing special support for initiatives that align with your authentic self and highest values. Trust in your unique cosmic blueprint as you navigate the opportunities and challenges of this period.`;
    }
  }
  
  // Default thoughtful response for other questions
  return "The cosmic energies surrounding your question reveal interesting patterns. I sense that you're at a significant juncture where your choices will have ripple effects beyond what might be immediately apparent. The current astrological climate supports introspection and honest self-assessment before making major decisions. There may be factors in your situation that haven't fully revealed themselves yet, so cultivating patience while remaining alert to synchronicities and subtle guidance would serve you well. Trust your intuitive impressions alongside practical considerations. The universe often speaks to us through repeated symbols, unexpected connections, and quiet moments of clarity. Remember that even periods of uncertainty contain valuable opportunities for growth and deeper self-understanding.";
};

// Helper function for zodiac traits
function getZodiacTraits(sign: string): string {
  const traits = {
    aries: "courage and pioneering spirit",
    taurus: "steadfastness and appreciation for beauty",
    gemini: "curiosity and communicative abilities",
    cancer: "nurturing nature and emotional intelligence",
    leo: "creativity and generosity",
    virgo: "attention to detail and practical wisdom",
    libra: "sense of harmony and diplomatic skills",
    scorpio: "intensity and transformative power",
    sagittarius: "optimism and philosophical perspective",
    capricorn: "discipline and ambition",
    aquarius: "innovation and humanitarian vision",
    pisces: "compassion and intuitive gifts"
  };
  
  return traits[sign as keyof typeof traits] || "unique qualities";
}
